### ISSUE TITLE
A few dead link references

### ISSUE THREAD

**Issue by bthaile** [onflow/docs#103]
These reference links fail, they need to be fixed or removed. 

https://academy.ecdao.org/EA_Iso.svg
https://chainmonsters.com/

**Comment by nialexsan** [comment]
add references
- http-api (node)
- testnet/mainnet endpoints
- other references in the docs
- unity reference
- cadence language functions reference
- fcl
- go
- flow status network

**Comment by nialexsan** [comment]
https://github.com/onflow/docs/pull/238
