### ISSUE TITLE
Update saved tutorial projects to not use `pub` or `priv` access modifiers

### ISSUE THREAD

**Issue by joshuahannan** [onflow/docs#148]
### Issue to be solved

We're removing `pub` and `priv` modifiers from the language and docs in https://github.com/onflow/docs/pull/146
so the saved playground projects for the tutorials need to also be updated. 

### Suggest A Solution

* Copy the projects for each tutorial
* Remove the access modifiers and replace them with `access(all)` and `access(self)`
* Save and export new projects
* add these links to their respective tutorials
* Test the links in incognito mode to make sure they are loading properly and that the contracts still deploy and transactions run properly

- [ ] Hello World
- [ ] Resources
- [ ] Capabilities
- [ ] NFT 1
- [ ] NFT 2
- [ ] FT
- [ ] Marketplace
- [ ] Voting
- [ ] Composable resources

**Comment by nialexsan** [comment]
currently the changes are reflected in the next version:
https://developers.flow.com/next/cadence/anti-patterns
