### ISSUE TITLE
[BUG] 404 page how-do-i-get-an-fusd-enabled-wallet

### ISSUE THREAD

**Issue by bz-hashtag-0780** [onflow/docs#205]
### Current Behavior

clicking on [How do I get an FUSD-enabled wallet?](https://docs.onflow.org/fusd/#how-do-i-get-an-fusd-enabled-wallet)  leads to a 404 page on developers.flow.com  https://developers.flow.com/fusd#how-do-i-get-an-fusd-enabled-wallet
<img width="485" alt="Screenshot 2023-08-21 at 10 25 50" src="https://github.com/onflow/docs/assets/88026162/b8f0366e-dd49-4cc8-bd4a-924ac56b2510">

### Expected Behavior

leading to a page that shows how to setup fusd wallet

### Steps To Reproduce

Try and fund testnet wallet with FUSD instead of Flow

<img width="700" alt="Screenshot 2023-08-21 at 10 27 06" src="https://github.com/onflow/docs/assets/88026162/d748a38b-1522-401b-8de5-17a66e1cf70e">

### Environment

```markdown
MacBook, Google Chrome
```

### What are you currently working on that this is blocking?

dApp on Flow that uses FUSD

**Comment by nialexsan** [comment]
FUSD has been deprecated and this token will be removed from the Flow Faucet
