### ISSUE TITLE
invalid flow command

### ISSUE THREAD

**Issue by bjartek** [onflow/docs#236]
### Current Behavior

https://developers.flow.com/tooling/flow-cli/utils/project-app 

this says you can use `flow app` but that command does not exist in v1.4.0

### Expected Behavior

that the commands in docs work

### Steps To Reproduce

run `flow app` 

### Environment

```markdown
mac flow-cli 1.4.0
```

### What are you currently working on that this is blocking?

helping people in discrod

**Comment by nialexsan** [comment]
we're currently reworking the documentation, the updated version is available here:
https://developers.flow.com/next/tools/toolchains/flow-cli
