### ISSUE TITLE
Deploying Smart Contracts [Docs Restructuring V1]

### ISSUE THREAD

**Issue by Aliserag** [onflow/docs#281]
### Issue to be solved

- [ ] Merge the following docs into a coherent single notion page: https://developers.flow.com/guides/deploying/mainnet-deployment and https://developers.flow.com/guides/deploying/testnet-deployment and  https://developers.flow.com/next/building-on-flow/flow-networks and https://developers.flow.com/guides/deploying

- [ ] Store it in the correct corresponding new layout section: https://www.notion.so/dapperlabs/Docs-Overhaul-d3071d324f89448f8ed4221838a878ae 

- [ ] Fix all links and ensure that previous links are redirected to the new location to avoid broken links and SEO issues.

- [ ] Get at least one of the following to proof read the docs:  Chase, Jeff, Tom, Ali or Greg.

**Comment by gregsantos** [comment]
Closing for slightly different approach:
https://developers.flow.com/guides/smart-contracts/overview
