### ISSUE TITLE
NFTs [Docs Restructuring V1] 

### ISSUE THREAD

**Issue by Aliserag** [onflow/docs#284]
### Issue to be solved

- [ ] Merge the following docs into a coherent single notion page:  https://developers.flow.com/cadence/tutorial/non-fungible-tokens-1 and https://developers.flow.com/cadence/tutorial/non-fungible-tokens-2 and https://developers.flow.com/guides/launchToken (NFT section)

- [ ] Store it in the correct corresponding new layout section: https://www.notion.so/dapperlabs/Docs-Overhaul-d3071d324f89448f8ed4221838a878ae 

- [ ] Fix all links and ensure that previous links are redirected to the new location to avoid broken links and SEO issues.

- [ ] Get at least one of the following to proof read the docs:  Chase, Jeff, Tom, Ali or Greg.

**Comment by gregsantos** [comment]
Closing in favor of **https://github.com/onflow/docs/issues/368**
