### ISSUE TITLE
Node Operation  [Docs Restructuring V1]

### ISSUE THREAD

**Issue by Aliserag** [onflow/docs#286]
### Issue to be solved

Currently the Node Operators (https://developers.flow.com/next/building-on-flow/run-and-secure/nodes/node-operation) and Flow Nodes (https://developers.flow.com/next/building-on-flow/run-and-secure/nodes) pages are identical and repetitive. 

- [ ] Replace all text in https://developers.flow.com/next/building-on-flow/run-and-secure/nodes/node-operation with something simple that introduces the concepts related to operating a node that they will discover in the sub sections.

- [ ] Store it in the correct corresponding new layout section: https://www.notion.so/dapperlabs/Docs-Overhaul-d3071d324f89448f8ed4221838a878ae 

- [ ] Fix all links and ensure that previous links are redirected to the new location to avoid broken links and SEO issues.

- [ ] Get at least one of the following to proof read the docs: Chase, Jeff, Tom, Ali or Greg.

**Comment by gregsantos** [comment]
Closing as completed by similar restructure
