### ISSUE TITLE
[BUG] Unresolveable link to operators.mdx

### ISSUE THREAD

**Issue by j1010001** [onflow/docs#372]
### Current Behavior

On the latest version I get this error when running locally:

`Error: Docs markdown link couldn't be resolved: (../references/run-and-secure/nodes/faq/operators.mdx) in "docs/versioned_docs/version-stable/cadence/measuring-time.mdx" for version stable`

### Expected Behavior

Link resolves

### Steps To Reproduce

Found in: 9e820553ccf24ab60c4b3372d80d2c79ccf70514 version

### Environment

```markdown
- OS:Local build on Mac
- Node: v18.17.0
- npm: 9.6.7
```

**Comment by bthaile** [comment]
redirect has been fixed. closing
