### ISSUE TITLE
flow accounts create --key ... does not add account to flow.json

### ISSUE THREAD

**Issue by bthaile** [onflow/docs#433]
The [flow-cli docs](https://developers.flow.com/tools/flow-cli/accounts/create-accounts) indicates that  `flow accounts create --key ...` will update the flow.json. This is not the case. 

Docs actually say this:
"In the above example, the flow.json file would look something like this: " 
We need to update the docs or fix flow-cli, I would think flow.json would get updated since the interactive mode does actually add the account.

**Comment by gregsantos** [comment]
@bthaile should be a CLI issue?
