### ISSUE TITLE
[FEATURE] Add core contract deployment addresses for Crescendo

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/docs#569]
### Issue to be solved

Core contract addresses are not currently listed from links branching from https://developers.flow.com/build/core-contracts

### Suggest A Solution

Find the crescendo addresses of all core contracts and update in the relevant docs pages

**Comment by sisyphusSmiling** [comment]
Realized testnet & crescendo share the same address space which was not intuitive to me since emulator, testnet and mainnet deployments typically have differing addresses. Perhaps we can add a `Crescendo/Testnet` label to the deployment address tables.

**Comment by bthaile** [comment]
We recently learned that "Crescendo" is the project/dev effort for cadence 1.0 and flow evm. The testnet network is going to be named `"Preview"` and prob become "Testnet" when the old testnet is abandoned.

**Comment by joshuahannan** [comment]
So should I just replace the `Testnet` entries in all of those tables with `Testnet/Previewnet/Crescendo/`?

**Comment by joshuahannan** [comment]
I made a PR to update these. Any reviews would be much appreciated! https://github.com/onflow/docs/pull/645

**Comment by joshuahannan** [comment]
Completed with https://github.com/onflow/docs/pull/645
