### ISSUE TITLE
[BUG] Update Cadence tutorials to ensure functionality with new Playground

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/docs#62]
### Current Behavior

Some tutorials have been found to not function well and/or guidance is out of sync with the new playground format.

### Expected Behavior

Written and visual guidance in the Cadence tutorial docs should align with the playground environment and any new Cadence features. Links should also direct to valid URLs.

### Steps To Reproduce

This is a general chore issue and does not refer to a specific instance of unexpected behavior.

### Environment

```markdown
- OS: N/A
- Node: N/A
- npm: N/A
```

**Comment by joshuahannan** [comment]
@bthaile I also noticed that when deploying the first contract in the hello world tutorial, the names of the transactions and scripts were overwritten as well. IDK if it is related to this.

To reproduce:

* Open the hello world code from the tutorial: https://play.flow.com/af7aba31-dee9-4477-9e1d-7b46e958468e
* See that the transaction is called "Simple Transaction" and the script is called "General Script"
* Deploy the HelloWorld contract in contract 1
* When the page refreshes, the transaction and script names have reverted to just "transaction" and "script"
