### ISSUE TITLE
Create Solidity Tutorial to use Cadence VRF

### ISSUE THREAD

**Issue by bthaile** [onflow/docs#641]
Add tutorial that outlines how solidity developers can get access to Cadence random number generator. 

1. Example solidity contract
2. Any cadence needed
3. Create simple UI to demo user guessing a number (1...10)
4. How transactions work, commit / reveal

**Comment by franklywatson** [comment]
This is great. However, based on recent discussions, this is likely only to be prioritized after the launch since adding Cadence VRF is additional scope beyond baseline EVM compatibility.

**Comment by bthaile** [comment]
Is this effort a protocol task or part of the cadence integration? Wondering if 4D could help.

**Comment by franklywatson** [comment]
It's going to require support and input from Tarak for the crypto-sec aspects and also possibly some lower level work in Cadence. Not clear at this point, but those who could support this aren't available for a bit

**Comment by bthaile** [comment]
This task has been done by @sisyphusSmiling
