### ISSUE TITLE
Add blog post and guide on Event streaming

### ISSUE THREAD

**Issue by UlyanaAndrukhiv** [onflow/docs#668]
### Issue to be solved

The current documentation lacks comprehensive guidance on event streaming, leading to confusion and inefficiencies among developers attempting to implement this feature.

### Suggest A Solution

To address this issue, the proposal involves creating a blog post and guide specifically focused on event streaming. The blog post will provide an overview of event streaming, including its significance, architecture, real-world use cases. Meanwhile, the guide will offer technical documentation and instructions for using event streaming.

**Comment by franklywatson** [comment]
Final review confirmed
