### ISSUE TITLE
Transferring Flow between Cadence and EVM

### ISSUE THREAD

**Issue by gregsantos** [onflow/docs#686]
COAs provide out of the box $FLOW token bridging between environments (see `deposit(from: @FlowToken.Vault)`). They are also powerful resources which integrate native cross-VM bridging capabilities through which applications can bridge arbitrary fungible and/or non-fungible tokens between Cadence and Flow EVM. Checkout the https://github.com/onflow/flips/pull/233improvement proposal for more details.

Note that transferring $FLOW from COAs to EOAs is not dependent on the VM bridge. This can be done in a similar manner to transfers in other EVM environments via a call without data transmitting value, as showcased below:

```java
/// Assuming the signer has a COA in storage & an EVM $FLOW balance to cover the amount specified...
transaction(to: EVM.EVMAddress, amount: UFix64) {
    prepare(signer: auth(BorrowValue) &Account) {
        let coa = signer.storage.borrow<&EVM.CadenceOwnedAccount>(from: /storage/evm)!
        coa.call(
            to: to,
            data: [],
            gasLimit: gasLimit,
            value: EVM.Balance().setFlow(flow: amount),
        )
    }
}

```

address(): EVMAddress returns the address of the smart contract, and the EVM address that is returned could be used to query balance, code, nonce, etc.

deposit(from: @FlowToken.Vault) allows depositing FLOW tokens into the smart contract (Cadence to Flow EVM). On the EVM side, the money for the deposits are always transfering from 0x0000000000000000000000010000000000000000 (native token bridge address). The balance of that address is adjusted before transfer.

withdraw(balance: Balance): @FlowToken.Vault allows withdrawing balance from the Flow EVM address and bridges it back as a FlowToken Vault to be handled on the Cadence side. On the EVM side, the money for the withdraw are always transfered to 0x0000000000000000000000010000000000000000 (native token bridge address) and then the balance of that address is adjusted.

**Comment by jribbink** [comment]
@gregsantos is this doc necessary?  It's already covered by https://github.com/onflow/docs/pull/758.

**Comment by gregsantos** [comment]
@jribbink that outa do, ty

**Comment by gregsantos** [comment]
completed in https://github.com/onflow/docs/pull/758
