### ISSUE TITLE
Final Review of IF Contacts

### ISSUE THREAD

**Issue by gregsantos** [onflow/docs#698]
We need to to a final check of contracts before multi-sig is final. This includes all contracts deployed to these accounts:
LendingPool.Flow - https://www.flowdiver.io/account/0x7492e2f9b4acea9a?tab=keys
LendingPool.FUSD - https://www.flowdiver.io/account/0x90f55b24a556ea45?tab=keys
LendingPool.USDC - https://www.flowdiver.io/account/0x8334275bda13b2be?tab=keys
LendingPool.BLT - https://www.flowdiver.io/account/0x67539e86cbe9b261?tab=keys
LendingPool.stFlow - https://www.flowdiver.io/account/0x44fe3d9157770b2d?tab=keys
LiquidStaking - https://www.flowdiver.io/account/0xd6f80565193ad727?tab=keys

We also need to make sure there are no obvious attack vectors from other accounts not listed here.

**Comment by sisyphusSmiling** [comment]
@nvdtf would you say this issue is closed?

**Comment by nvdtf** [comment]
@sisyphusSmiling I think so. We checked and there were no updates since last time we reviewed per the Notion doc.
