### ISSUE TITLE
Testing Previewnet EVM with more complex EVM contracts

### ISSUE THREAD

**Issue by nvdtf** [onflow/docs#713]
### Issue to be solved

We're planning to test our EVM implementation with a couple of more complex Solidity contracts. We plan to deploy:
* Cheeze Wizards
* Uniswap-v3

And try to uncover any early issues.

**Comment by ianthpun** [comment]
some updates 

https://github.com/NomicFoundation/hardhat-ignition/issues/738

Hardhat ignition still has some issues wit hthe flow node that we haven't figured out just yet. Best to continue this conversation to figure out whats missing

**Comment by nvdtf** [comment]
Deployed Uniswap v4-core [PoolManager](https://github.com/sanamummer/Uniswap-v4/blob/main/contracts/PoolManager.sol) to PreviewNet successfully.

The current issue is that we need to use `--legacy` with Foundry to disable EIP-1559 style transactions. We're working to fix this as well so the deployment scripts work out-of-the-box:
https://github.com/onflow/flow-evm-gateway/issues/208

Currently waiting for new gateway deployment to test further.

**Comment by nvdtf** [comment]
Reported https://github.com/onflow/flow-evm-gateway/issues/247 for adding `script` for Foundry

**Comment by nvdtf** [comment]
Continuing with USDC deployment on PreviewNet, reported https://github.com/onflow/flow-evm-gateway/issues/273

**Comment by nvdtf** [comment]
Successfully deployed USDC https://github.com/circlefin/stablecoin-evm/

**Comment by ianthpun** [comment]
Cheeze wizards presale contract was a success in deployment. I did hit some snags on using hardhat, but ultimately did deploy and was able to interact and buy wizards
