### ISSUE TITLE
[FEATURE] Update Core Contracts

### ISSUE THREAD

**Issue by jribbink** [onflow/docs#756]
### Issue to be solved

Currently, the core contracts page has a few issues/missing information.

1. There's duplicates of the FT/NFT pages
2. Most of the Core Contracts do not have reference documentation
3. The FT/NFT docs are partially being pulled in via remote repositories.  These are just generated docs and if we could avoid this, I think that it is ideal.  Seems like unnecessary overhead for something that could just be generated locally instead

We should also try to update these docs on the Cadence 1.0 branch of the docs site.

### Suggest A Solution

We should revive the [Cadence Docugen Tool](https://github.com/onflow/cadence-tools/tree/master/docgen) and use this to generate our docs (it is not updated to Cadence 1.0 yet).  IMO 99% of the "Core Contracts" pages could be automatically generated.

Each API reference doc should contain the following:
 - Any custom description/information (e.g. if we want to link people to GitHub repositories, tutorials, etc.)
 - Network addresses
 - Auto-generated API reference documentation
 
 Ideally this exists in a auto-generated, and configurable way so that we can have consistency across these API reference docs and they do not begin to drift again.

### What are you currently working on that this is blocking?

Writing guides for EVM contract.  There's lots of custom structs, resources, events, and less-commonly used functions that do not necessarily belong in every guide themselves, but deserve some sort of reference on our docs site (e.g. something we can link to so devs know accurate type information/what else they can do)

**Comment by joshuahannan** [comment]
I can work on this next week

**Comment by joshuahannan** [comment]
I simplified all the pages in this PR: https://github.com/onflow/docs/pull/780

IMO these pages should only be a quick reference for the import addresses and some basic info about events. Full docs for the contracts should live in their respective github repos or sections of the docs site. That is how I did it in my PR
