### ISSUE TITLE
Create Dashboard for Testnet Transaction Events

### ISSUE THREAD

**Issue by gregsantos** [onflow/docs#775]
### Transaction Inspection Logic

1. Introduction:
Transaction Inspection Logic is a feature designed to enhance the integrity and security of the Cadence 1.0 migration process. By carefully evaluating each transaction, this system helps detect and mitigate issues early, ensuring a smoother migration experience.

[PRD](https://www.notion.so/flowfoundation/Transaction-Inspector-Dashboard-PRD-d1a8f89202904825be7d6e399f91ebce)

**Comment by ianthpun** [comment]
Informed that Flipside does not currently support Testnet (yet), and we won't know if we're going to get that support until atleaest the 17th when the lead developer is back
