### ISSUE TITLE
Update CLI Install Docs

### ISSUE THREAD

**Issue by gregsantos** [onflow/docs#819]
Docs need to be updated removing install instructions for c1 CLI
All repos are now Cadence 1.0 on their main branch

- https://cadence-lang.org/docs/1.0/cadence-migration-guide#install-cadence-10-cli

**Comment by turbolent** [comment]
Here's a list of all places that need to get updated: https://github.com/search?q=org%3Aonflow%20feature%2Fstable-cadence&type=code

Note that these aren't just documentation, but also CI configurations
