### ISSUE TITLE
Differences between Flow EVM and Ethereum

### ISSUE THREAD

**Issue by ramtinms** [onflow/docs#821]
We have covered many topics from Flow perspective (e.g. [the filp](https://github.com/onflow/flips/blob/main/protocol/20231116-evm-support.md) ), but we need some docs on differences between FLOW EVM and Ethereum, we have received many questions in the past and I want to aggregate them into a single document mostly targeting EVM devs. 

Subsections will be added soon.

**Comment by franklywatson** [comment]
I would like to contribute some thoughts about how to think about translating from EVM standards to Cadence
